service: inderes-tracker
frameworkVersion: ">=2.17.0 <3.0.0"

custom:
  credentialsProfile: heap
  region: eu-west-1
  secret: ${file(secrets.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  profile: ${self:custom.credentialsProfile}
  environment:
    TELEGRAM_BOT_AUTH_TOKEN: ${self:custom.secret.telegram_bot_auth_token}
    TELEGRAM_CHAT_ID: ${self:custom.secret.telegram_chat_id}

functions:
  trackAnalysis:
    handler: dist/index.handler
    memorySize: 128
    timeout: 20
    events:
      - schedule: cron(55 7 ? * * *) # 9.55am during winter, 10.55am during summer in Finland

package:
  exclude:
    - "**"
  include:
    - "dist/**"
    - "node_modules/**"
