service: inderes-tracker
frameworkVersion: ">=3.21.0 <4.0.0"

custom:
  credentialsProfile: heap
  region: eu-west-1
  secret: ${file(secrets.yml)}

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.region}
  profile: ${self:custom.credentialsProfile}
  environment:
    TELEGRAM_BOT_AUTH_TOKEN: ${self:custom.secret.telegram_bot_auth_token}
    TELEGRAM_CHAT_ID: ${self:custom.secret.telegram_chat_id}

functions:
  trackAnalysis:
    handler: dist/index.handler
    memorySize: 128
    timeout: 60
    events:
      - schedule: cron(55 6 ? * * *) # 8.55am during winter, 9.55am during summer in Finland

package:
  patterns:
    - "!*"
    - "dist/**"
    - "node_modules/**"
